#!/usr/bin/env bash
set -e

# Spotify Tray for Hyprland - Setup Script
# Installs tray icon with scroll/middle-click support

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config"
APPS_DIR="$HOME/.local/share/applications"

echo "=== Spotify Tray Setup ==="

# 1. Build the tray application
echo "[1/5] Building spotify-tray..."
cd "$SCRIPT_DIR/spotify-tray-wayland"
go build -o spotify-tray-wayland .
echo "      Built successfully"

# 2. Install binaries to ~/.local/bin
echo "[2/5] Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
cp spotify-tray-wayland "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/spotify-tray-wayland"

# Create launcher script
cat > "$INSTALL_DIR/spotify-launcher.sh" << 'EOF'
#!/usr/bin/env bash
# Spotify Launcher - starts tray with Spotify

# Start tray if not running
if ! pgrep -f spotify-tray-wayland >/dev/null; then
    ~/.local/bin/spotify-tray-wayland &
fi

# Start Spotify
exec spotify "$@"
EOF
chmod +x "$INSTALL_DIR/spotify-launcher.sh"
echo "      Installed binaries"

# 3. Create desktop entry (overrides system Spotify)
echo "[3/5] Creating desktop entry..."
mkdir -p "$APPS_DIR"
cat > "$APPS_DIR/spotify.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Music Player
Icon=spotify
TryExec=spotify
Exec=$INSTALL_DIR/spotify-launcher.sh %U
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify
EOF
update-desktop-database "$APPS_DIR" 2>/dev/null || true
echo "      Created desktop entry"

# 4. Create Hyprland config snippet
echo "[4/5] Configuring Hyprland..."
mkdir -p "$CONFIG_DIR/hypr/conf.d"
cat > "$CONFIG_DIR/hypr/conf.d/spotify.conf" << 'EOF'
# Spotify Tray Configuration
# Auto-generated by spotify-tray setup script

# Tray starts with Spotify via ~/.local/bin/spotify-launcher.sh

# Super+M: Minimize focused window to special workspace
bind = SUPER, M, movetoworkspacesilent, special:minimized

# Super+` (grave): Show minimized windows
bind = SUPER, grave, togglespecialworkspace, minimized
EOF

# Check if conf.d is sourced in main config
if ! grep -q "source.*conf.d" "$CONFIG_DIR/hypr/hyprland.conf" 2>/dev/null; then
    echo "" >> "$CONFIG_DIR/hypr/hyprland.conf"
    echo "# Source additional configs" >> "$CONFIG_DIR/hypr/hyprland.conf"
    echo "source = ~/.config/hypr/conf.d/*.conf" >> "$CONFIG_DIR/hypr/hyprland.conf"
    echo "      Added conf.d source to hyprland.conf"
fi
echo "      Created Hyprland config"

# 5. Cleanup old autostart (tray now starts with Spotify)
echo "[5/5] Cleaning up..."
rm -f "$CONFIG_DIR/autostart/spotify-tray.desktop" 2>/dev/null
echo "      Done"

# Reload Hyprland config
hyprctl reload 2>/dev/null || true

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Features:"
echo "  - Tray icon starts WITH Spotify (not at login)"
echo "  - Scroll up/down: Next/Previous track"
echo "  - Middle-click: Play/Pause"
echo "  - Show/Hide menu: Toggle Spotify window"
echo ""
echo "Keybinds:"
echo "  - Super+M: Minimize any window"
echo "  - Super+\`: Show minimized windows"
echo ""
echo "Launch Spotify from your app menu to test!"
