#!/usr/bin/env bash
set -e

# Spotify Tray for Hyprland - Setup Script
# Installs tray icon with scroll/middle-click support and smart-close keybind

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config"
APPS_DIR="$HOME/.local/share/applications"
HYPR_SCRIPTS="$CONFIG_DIR/hypr/UserScripts"
HYPR_DIR="$CONFIG_DIR/hypr"

echo "=== Spotify Tray Setup ==="

# Detect user's killactive keybind
detect_killactive_keybind() {
    local killactive_line modifier key

    # Search all hyprland configs for killactive binding
    killactive_line=$(grep -rh "killactive" "$HYPR_DIR" 2>/dev/null | grep -E "^bind" | head -1)

    if [[ -z "$killactive_line" ]]; then
        # Default fallback
        echo "SUPER Q"
        return
    fi

    # Extract modifier and key from bind line
    # Format: bind[d] = MODIFIER, KEY, [description,] killactive
    # Remove everything after the = and parse
    local bind_part=$(echo "$killactive_line" | sed 's/.*=\s*//' | tr -d ' ')

    # Get first two comma-separated values (modifier, key)
    modifier=$(echo "$bind_part" | cut -d',' -f1)
    key=$(echo "$bind_part" | cut -d',' -f2)

    # Resolve $mainMod variable if present
    if [[ "$modifier" == *'$mainMod'* ]] || [[ "$modifier" == *'${mainMod}'* ]]; then
        # Find mainMod definition
        local mainmod_def=$(grep -rh '^\$mainMod\s*=' "$HYPR_DIR" 2>/dev/null | head -1 | sed 's/.*=\s*//' | tr -d ' ')
        mainmod_def=${mainmod_def:-SUPER}
        modifier=$(echo "$modifier" | sed "s/\\\$mainMod/$mainmod_def/g" | sed "s/\${mainMod}/$mainmod_def/g")
    fi

    echo "$modifier $key"
}

echo "[0/6] Detecting keybinds..."
read -r CLOSE_MOD CLOSE_KEY <<< "$(detect_killactive_keybind)"
echo "      Found killactive keybind: $CLOSE_MOD + $CLOSE_KEY"

# 1. Build the tray application
echo "[1/6] Building spotify-tray..."
cd "$SCRIPT_DIR/spotify-tray-wayland"
go build -o spotify-tray-wayland .
echo "      Built successfully"

# 2. Install binaries to ~/.local/bin
echo "[2/6] Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
cp spotify-tray-wayland "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/spotify-tray-wayland"

# Create launcher script
cat > "$INSTALL_DIR/spotify-launcher.sh" << 'EOF'
#!/usr/bin/env bash
# Spotify Launcher - starts tray with Spotify

# Start tray if not running
if ! pgrep -f spotify-tray-wayland >/dev/null; then
    ~/.local/bin/spotify-tray-wayland &
fi

# Start Spotify
exec spotify "$@"
EOF
chmod +x "$INSTALL_DIR/spotify-launcher.sh"
echo "      Installed binaries"

# 3. Create desktop entry (overrides system Spotify)
echo "[3/6] Creating desktop entry..."
mkdir -p "$APPS_DIR"
cat > "$APPS_DIR/spotify.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Music Player
Icon=spotify
TryExec=spotify
Exec=$INSTALL_DIR/spotify-launcher.sh %U
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify
EOF
update-desktop-database "$APPS_DIR" 2>/dev/null || true
echo "      Created desktop entry"

# 4. Install smart-close script (Super+Q minimizes Spotify, kills other windows)
echo "[4/6] Installing smart-close script..."
mkdir -p "$HYPR_SCRIPTS"
cat > "$HYPR_SCRIPTS/smart-close.sh" << 'EOF'
#!/bin/bash
# Smart close: minimize Spotify to tray, kill other windows
# Part of spotify-tray-wayland

class=$(hyprctl activewindow | grep "class:" | cut -d' ' -f2)

if [[ "${class,,}" == "spotify" ]]; then
    hyprctl dispatch movetoworkspacesilent special:minimized
else
    hyprctl dispatch killactive
fi
EOF
chmod +x "$HYPR_SCRIPTS/smart-close.sh"
echo "      Installed smart-close script"

# 5. Create Hyprland config snippet
echo "[5/6] Configuring Hyprland keybinds..."
mkdir -p "$CONFIG_DIR/hypr/conf.d"
cat > "$CONFIG_DIR/hypr/conf.d/spotify.conf" << EOF
# Spotify Tray Configuration
# Auto-generated by spotify-tray setup script

# Smart close: minimize Spotify to tray, kill other windows
# Detected keybind: $CLOSE_MOD + $CLOSE_KEY
unbind = $CLOSE_MOD, $CLOSE_KEY
bind = $CLOSE_MOD, $CLOSE_KEY, exec, ~/.config/hypr/UserScripts/smart-close.sh

# Super+M: Minimize focused window to special workspace
bind = SUPER, M, movetoworkspacesilent, special:minimized

# Super+\` (grave): Show minimized windows
bind = SUPER, grave, togglespecialworkspace, minimized
EOF

# Check if conf.d is sourced in main config
if ! grep -q "source.*conf.d" "$CONFIG_DIR/hypr/hyprland.conf" 2>/dev/null; then
    echo "" >> "$CONFIG_DIR/hypr/hyprland.conf"
    echo "# Source additional configs" >> "$CONFIG_DIR/hypr/hyprland.conf"
    echo "source = ~/.config/hypr/conf.d/*.conf" >> "$CONFIG_DIR/hypr/hyprland.conf"
    echo "      Added conf.d source to hyprland.conf"
fi
echo "      Created Hyprland config"

# 6. Cleanup old autostart (tray now starts with Spotify)
echo "[6/6] Cleaning up..."
rm -f "$CONFIG_DIR/autostart/spotify-tray.desktop" 2>/dev/null
echo "      Done"

# Reload Hyprland config
hyprctl reload 2>/dev/null || true

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Features:"
echo "  - Tray icon starts WITH Spotify (not at login)"
echo "  - Scroll up/down: Next/Previous track"
echo "  - Middle-click: Play/Pause"
echo "  - Show/Hide menu: Toggle Spotify window"
echo "  - $CLOSE_MOD+$CLOSE_KEY: Minimizes Spotify to tray (kills other windows)"
echo ""
echo "Keybinds:"
echo "  - $CLOSE_MOD+$CLOSE_KEY: Smart close (minimize Spotify / kill others)"
echo "  - Super+M: Minimize any window"
echo "  - Super+\`: Show minimized windows"
echo ""
echo "Launch Spotify from your app menu to test!"
